-- MySQL Script generated by MySQL Workbench
-- 06/19/18 12:03:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema kristen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kristen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kristen` DEFAULT CHARACTER SET utf8 ;
USE `kristen` ;

-- -----------------------------------------------------
-- Table `kristen`.`Carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Carreras` (
  `idCarreras` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idCarreras`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Tipos_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Tipos_Usuario` (
  `idTipos_Usuario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `idCarreras` INT NULL,
  PRIMARY KEY (`idTipos_Usuario`),
  INDEX `idCarreras_idx` (`idCarreras` ASC),
  CONSTRAINT `idCarreras`
    FOREIGN KEY (`idCarreras`)
    REFERENCES `kristen`.`Carreras` (`idCarreras`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Usuarios` (
  `idUsuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `contrasena` VARCHAR(12) NULL,
  `correo` VARCHAR(45) NULL,
  `idTipos_Usuarios` INT NULL,
  PRIMARY KEY (`idUsuarios`),
  INDEX `idTipos_Usuario_idx` (`idTipos_Usuarios` ASC),
  CONSTRAINT `idTipos_Usuario`
    FOREIGN KEY (`idTipos_Usuarios`)
    REFERENCES `kristen`.`Tipos_Usuario` (`idTipos_Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Tipos_Informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Tipos_Informacion` (
  `idTipos_Informacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipos_Informacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Informacion_Institucional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Informacion_Institucional` (
  `idInformacion_Institucional` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `portada` VARCHAR(45) NULL,
  `categorias` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `idTipos_Informacion` INT NULL,
  `idUsuarios` INT NULL,
  PRIMARY KEY (`idInformacion_Institucional`),
  INDEX `idTipos_Informacion_idx` (`idTipos_Informacion` ASC),
  INDEX `idUsuarios_idx` (`idUsuarios` ASC),
  CONSTRAINT `idTipos_Informacion`
    FOREIGN KEY (`idTipos_Informacion`)
    REFERENCES `kristen`.`Tipos_Informacion` (`idTipos_Informacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Usuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `kristen`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Tipos_Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Tipos_Publicacion` (
  `idTipos_Publicacion` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipos_Publicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Publicaciones` (
  `idPublicaciones` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `descripcion` VARCHAR(250) NULL,
  `portada` VARCHAR(200) NULL,
  `categorias` VARCHAR(45) NULL,
  `subtitulo` VARCHAR(45) NULL,
  `prioridad` INT NULL,
  `idTipos_Publicacion` INT NULL,
  `idUsuarios` INT NULL,
  PRIMARY KEY (`idPublicaciones`),
  INDEX `idTipos_Publicacion_idx` (`idTipos_Publicacion` ASC),
  INDEX `idUsuarios_idx` (`idUsuarios` ASC),
  CONSTRAINT `idTipos_Publicacion`
    FOREIGN KEY (`idTipos_Publicacion`)
    REFERENCES `kristen`.`Tipos_Publicacion` (`idTipos_Publicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idUsuarios`
    FOREIGN KEY (`idUsuarios`)
    REFERENCES `kristen`.`Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Tipos_Contenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Tipos_Contenidos` (
  `idTipos_Contenidos` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idTipos_Contenidos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Contenidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Contenidos` (
  `idContenidos` INT NOT NULL,
  `str_contenido` LONGTEXT NULL,
  `idTipoContenidos` INT NULL,
  PRIMARY KEY (`idContenidos`),
  INDEX `idTipoContenidos_idx` (`idTipoContenidos` ASC),
  CONSTRAINT `idTipoContenidos`
    FOREIGN KEY (`idTipoContenidos`)
    REFERENCES `kristen`.`Tipos_Contenidos` (`idTipos_Contenidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `kristen`.`Publicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Publicacion` (
  `idPublicacion` INT NOT NULL,
  `idPublicaciones` INT NULL,
  `idContenidos` INT NULL,
  PRIMARY KEY (`idPublicacion`),
  INDEX `idContenidos_idx` (`idContenidos` ASC),
  INDEX `idPublicaciones_idx` (`idPublicaciones` ASC),
  CONSTRAINT `idContenidos`
    FOREIGN KEY (`idContenidos`)
    REFERENCES `kristen`.`Contenidos` (`idContenidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_Publicaciones`
    FOREIGN KEY (`idPublicaciones`)
    REFERENCES `kristen`.`Publicaciones` (`idPublicaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `kristen`.`Informacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kristen`.`Informacion` (
  `idInformacion` INT NOT NULL,
  `idInformacion_Institucional` INT NULL,
  `idContenidos` INT NULL,
  INDEX `idContenidos_idx` (`idContenidos` ASC),
  INDEX `idInformacion_Institucional_idx` (`idInformacion_Institucional` ASC),
  CONSTRAINT `id_Contenidos`
    FOREIGN KEY (`idContenidos`)
    REFERENCES `kristen`.`Contenidos` (`idContenidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idInformacion_Institucional`
    FOREIGN KEY (`idInformacion_Institucional`)
    REFERENCES `kristen`.`Informacion_Institucional` (`idInformacion_Institucional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
